//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfGraficiVezhba
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureWorksDW2017DBO : DbContext
    {
        public AdventureWorksDW2017DBO()
            : base("name=AdventureWorksDW2017DBO")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DatabaseLog> DatabaseLog { get; set; }
        public DbSet<DimAccount> DimAccount { get; set; }
        public DbSet<DimCurrency> DimCurrency { get; set; }
        public DbSet<DimCustomer> DimCustomer { get; set; }
        public DbSet<DimDate> DimDate { get; set; }
        public DbSet<DimDepartmentGroup> DimDepartmentGroup { get; set; }
        public DbSet<DimEmployee> DimEmployee { get; set; }
        public DbSet<DimGeography> DimGeography { get; set; }
        public DbSet<DimOrganization> DimOrganization { get; set; }
        public DbSet<DimProduct> DimProduct { get; set; }
        public DbSet<DimProductCategory> DimProductCategory { get; set; }
        public DbSet<DimProductSubcategory> DimProductSubcategory { get; set; }
        public DbSet<DimPromotion> DimPromotion { get; set; }
        public DbSet<DimReseller> DimReseller { get; set; }
        public DbSet<DimSalesReason> DimSalesReason { get; set; }
        public DbSet<DimSalesTerritory> DimSalesTerritory { get; set; }
        public DbSet<DimScenario> DimScenario { get; set; }
        public DbSet<FactAdditionalInternationalProductDescription> FactAdditionalInternationalProductDescription { get; set; }
        public DbSet<FactCallCenter> FactCallCenter { get; set; }
        public DbSet<FactCurrencyRate> FactCurrencyRate { get; set; }
        public DbSet<FactInternetSales> FactInternetSales { get; set; }
        public DbSet<FactProductInventory> FactProductInventory { get; set; }
        public DbSet<FactResellerSales> FactResellerSales { get; set; }
        public DbSet<FactSalesQuota> FactSalesQuota { get; set; }
        public DbSet<FactSurveyResponse> FactSurveyResponse { get; set; }
        public DbSet<ProspectiveBuyer> ProspectiveBuyer { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<FactFinance> FactFinance { get; set; }
    }
}
