//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfGraficiVezhba.NBRMKursnaListaVebServis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.nbrm.mk/klservice/", ConfigurationName="NBRMKursnaListaVebServis.KursSoap")]
    public interface KursSoap {
        
        // CODEGEN: Generating message contract since element name GetExchangeRateDResult from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRateD", ReplyAction="*")]
        WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDResponse GetExchangeRateD(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRateD", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDResponse> GetExchangeRateDAsync(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequest request);
        
        // CODEGEN: Generating message contract since element name StartDate from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRate", ReplyAction="*")]
        WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateResponse GetExchangeRate(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRate", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateResponse> GetExchangeRateAsync(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequest request);
        
        // CODEGEN: Generating message contract since element name GetExchangeRatesDResult from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRatesD", ReplyAction="*")]
        WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDResponse GetExchangeRatesD(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRatesD", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDResponse> GetExchangeRatesDAsync(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequest request);
        
        // CODEGEN: Generating message contract since element name StartDate from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRates", ReplyAction="*")]
        WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesResponse GetExchangeRates(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRates", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesResponse> GetExchangeRatesAsync(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateD", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequestBody Body;
        
        public GetExchangeRateDRequest() {
        }
        
        public GetExchangeRateDRequest(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime EndDate;
        
        public GetExchangeRateDRequestBody() {
        }
        
        public GetExchangeRateDRequestBody(System.DateTime StartDate, System.DateTime EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateDResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDResponseBody Body;
        
        public GetExchangeRateDResponse() {
        }
        
        public GetExchangeRateDResponse(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRateDResult;
        
        public GetExchangeRateDResponseBody() {
        }
        
        public GetExchangeRateDResponseBody(string GetExchangeRateDResult) {
            this.GetExchangeRateDResult = GetExchangeRateDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRate", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequestBody Body;
        
        public GetExchangeRateRequest() {
        }
        
        public GetExchangeRateRequest(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndDate;
        
        public GetExchangeRateRequestBody() {
        }
        
        public GetExchangeRateRequestBody(string StartDate, string EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateResponseBody Body;
        
        public GetExchangeRateResponse() {
        }
        
        public GetExchangeRateResponse(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRateResult;
        
        public GetExchangeRateResponseBody() {
        }
        
        public GetExchangeRateResponseBody(string GetExchangeRateResult) {
            this.GetExchangeRateResult = GetExchangeRateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesD", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequestBody Body;
        
        public GetExchangeRatesDRequest() {
        }
        
        public GetExchangeRatesDRequest(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime EndDate;
        
        public GetExchangeRatesDRequestBody() {
        }
        
        public GetExchangeRatesDRequestBody(System.DateTime StartDate, System.DateTime EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesDResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDResponseBody Body;
        
        public GetExchangeRatesDResponse() {
        }
        
        public GetExchangeRatesDResponse(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesDResult;
        
        public GetExchangeRatesDResponseBody() {
        }
        
        public GetExchangeRatesDResponseBody(string GetExchangeRatesDResult) {
            this.GetExchangeRatesDResult = GetExchangeRatesDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRates", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequestBody Body;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndDate;
        
        public GetExchangeRatesRequestBody() {
        }
        
        public GetExchangeRatesRequestBody(string StartDate, string EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesResponseBody Body;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesResult;
        
        public GetExchangeRatesResponseBody() {
        }
        
        public GetExchangeRatesResponseBody(string GetExchangeRatesResult) {
            this.GetExchangeRatesResult = GetExchangeRatesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KursSoapChannel : WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KursSoapClient : System.ServiceModel.ClientBase<WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap>, WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap {
        
        public KursSoapClient() {
        }
        
        public KursSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KursSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KursSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KursSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDResponse WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap.GetExchangeRateD(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequest request) {
            return base.Channel.GetExchangeRateD(request);
        }
        
        public string GetExchangeRateD(System.DateTime StartDate, System.DateTime EndDate) {
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequest inValue = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequest();
            inValue.Body = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDResponse retVal = ((WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap)(this)).GetExchangeRateD(inValue);
            return retVal.Body.GetExchangeRateDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDResponse> WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap.GetExchangeRateDAsync(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequest request) {
            return base.Channel.GetExchangeRateDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDResponse> GetExchangeRateDAsync(System.DateTime StartDate, System.DateTime EndDate) {
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequest inValue = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequest();
            inValue.Body = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap)(this)).GetExchangeRateDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateResponse WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap.GetExchangeRate(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequest request) {
            return base.Channel.GetExchangeRate(request);
        }
        
        public string GetExchangeRate(string StartDate, string EndDate) {
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequest inValue = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequest();
            inValue.Body = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateResponse retVal = ((WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap)(this)).GetExchangeRate(inValue);
            return retVal.Body.GetExchangeRateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateResponse> WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap.GetExchangeRateAsync(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequest request) {
            return base.Channel.GetExchangeRateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateResponse> GetExchangeRateAsync(string StartDate, string EndDate) {
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequest inValue = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequest();
            inValue.Body = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRateRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap)(this)).GetExchangeRateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDResponse WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap.GetExchangeRatesD(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequest request) {
            return base.Channel.GetExchangeRatesD(request);
        }
        
        public string GetExchangeRatesD(System.DateTime StartDate, System.DateTime EndDate) {
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequest inValue = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequest();
            inValue.Body = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDResponse retVal = ((WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap)(this)).GetExchangeRatesD(inValue);
            return retVal.Body.GetExchangeRatesDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDResponse> WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap.GetExchangeRatesDAsync(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequest request) {
            return base.Channel.GetExchangeRatesDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDResponse> GetExchangeRatesDAsync(System.DateTime StartDate, System.DateTime EndDate) {
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequest inValue = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequest();
            inValue.Body = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap)(this)).GetExchangeRatesDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesResponse WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap.GetExchangeRates(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public string GetExchangeRates(string StartDate, string EndDate) {
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequest inValue = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequest();
            inValue.Body = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesResponse retVal = ((WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap)(this)).GetExchangeRates(inValue);
            return retVal.Body.GetExchangeRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesResponse> WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap.GetExchangeRatesAsync(WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesResponse> GetExchangeRatesAsync(string StartDate, string EndDate) {
            WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequest inValue = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequest();
            inValue.Body = new WpfGraficiVezhba.NBRMKursnaListaVebServis.GetExchangeRatesRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WpfGraficiVezhba.NBRMKursnaListaVebServis.KursSoap)(this)).GetExchangeRatesAsync(inValue);
        }
    }
}
